Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Naming/MethodParameterName:
  MinNameLength: 1

Layout/HashAlignment:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
